export declare const adminUsers: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "admin_users";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "admin_users";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        username: import("drizzle-orm/pg-core").PgColumn<{
            name: "username";
            tableName: "admin_users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        email: import("drizzle-orm/pg-core").PgColumn<{
            name: "email";
            tableName: "admin_users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        passwordHash: import("drizzle-orm/pg-core").PgColumn<{
            name: "password_hash";
            tableName: "admin_users";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        fullName: import("drizzle-orm/pg-core").PgColumn<{
            name: "full_name";
            tableName: "admin_users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        role: import("drizzle-orm/pg-core").PgColumn<{
            name: "role";
            tableName: "admin_users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        status: import("drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "admin_users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        lastLogin: import("drizzle-orm/pg-core").PgColumn<{
            name: "last_login";
            tableName: "admin_users";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "admin_users";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "admin_users";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const expertPersonas: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "expert_personas";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        adminUserId: import("drizzle-orm/pg-core").PgColumn<{
            name: "admin_user_id";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        expertName: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_name";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        expertStatus: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_status";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        expertiseFocus: import("drizzle-orm/pg-core").PgColumn<{
            name: "expertise_focus";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        targetBuyerSegments: import("drizzle-orm/pg-core").PgColumn<{
            name: "target_buyer_segments";
            tableName: "expert_personas";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        authorityLevel: import("drizzle-orm/pg-core").PgColumn<{
            name: "authority_level";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        professionalBackgroundEncrypted: import("drizzle-orm/pg-core").PgColumn<{
            name: "professional_background_encrypted";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        expertiseCredentialsEncrypted: import("drizzle-orm/pg-core").PgColumn<{
            name: "expertise_credentials_encrypted";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        marketExperienceEncrypted: import("drizzle-orm/pg-core").PgColumn<{
            name: "market_experience_encrypted";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        primaryMarketLocation: import("drizzle-orm/pg-core").PgColumn<{
            name: "primary_market_location";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        secondaryMarketAreas: import("drizzle-orm/pg-core").PgColumn<{
            name: "secondary_market_areas";
            tableName: "expert_personas";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        localMarketKnowledgeDepth: import("drizzle-orm/pg-core").PgColumn<{
            name: "local_market_knowledge_depth";
            tableName: "expert_personas";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        timezone: import("drizzle-orm/pg-core").PgColumn<{
            name: "timezone";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        geoContentSpecializations: import("drizzle-orm/pg-core").PgColumn<{
            name: "geo_content_specializations";
            tableName: "expert_personas";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        authorityBuildingTopics: import("drizzle-orm/pg-core").PgColumn<{
            name: "authority_building_topics";
            tableName: "expert_personas";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        citationWorthyExpertise: import("drizzle-orm/pg-core").PgColumn<{
            name: "citation_worthy_expertise";
            tableName: "expert_personas";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        platformExpertiseFocus: import("drizzle-orm/pg-core").PgColumn<{
            name: "platform_expertise_focus";
            tableName: "expert_personas";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        contentPublicationSchedule: import("drizzle-orm/pg-core").PgColumn<{
            name: "content_publication_schedule";
            tableName: "expert_personas";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        expertVoiceCharacteristics: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_voice_characteristics";
            tableName: "expert_personas";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        personaEncryptionKeyId: import("drizzle-orm/pg-core").PgColumn<{
            name: "persona_encryption_key_id";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        browserFingerprintConfig: import("drizzle-orm/pg-core").PgColumn<{
            name: "browser_fingerprint_config";
            tableName: "expert_personas";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        currentAuthorityScore: import("drizzle-orm/pg-core").PgColumn<{
            name: "current_authority_score";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        estimatedAiCitations: import("drizzle-orm/pg-core").PgColumn<{
            name: "estimated_ai_citations";
            tableName: "expert_personas";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        expertRecognitionSignals: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_recognition_signals";
            tableName: "expert_personas";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        thoughtLeadershipReach: import("drizzle-orm/pg-core").PgColumn<{
            name: "thought_leadership_reach";
            tableName: "expert_personas";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        monthlyConsultationRequests: import("drizzle-orm/pg-core").PgColumn<{
            name: "monthly_consultation_requests";
            tableName: "expert_personas";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        consultationToReferralRate: import("drizzle-orm/pg-core").PgColumn<{
            name: "consultation_to_referral_rate";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        averageConsultationValue: import("drizzle-orm/pg-core").PgColumn<{
            name: "average_consultation_value";
            tableName: "expert_personas";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "expert_personas";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "expert_personas";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        lastExpertActivity: import("drizzle-orm/pg-core").PgColumn<{
            name: "last_expert_activity";
            tableName: "expert_personas";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const geoPlatformAccounts: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "geo_platform_accounts";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        personaId: import("drizzle-orm/pg-core").PgColumn<{
            name: "persona_id";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        platformType: import("drizzle-orm/pg-core").PgColumn<{
            name: "platform_type";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        platformPriority: import("drizzle-orm/pg-core").PgColumn<{
            name: "platform_priority";
            tableName: "geo_platform_accounts";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        geoOptimizationLevel: import("drizzle-orm/pg-core").PgColumn<{
            name: "geo_optimization_level";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        username: import("drizzle-orm/pg-core").PgColumn<{
            name: "username";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        displayName: import("drizzle-orm/pg-core").PgColumn<{
            name: "display_name";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        expertBio: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_bio";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        expertCredentials: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_credentials";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        profileOptimizationScore: import("drizzle-orm/pg-core").PgColumn<{
            name: "profile_optimization_score";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        credentialsEncrypted: import("drizzle-orm/pg-core").PgColumn<{
            name: "credentials_encrypted";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        authTokensEncrypted: import("drizzle-orm/pg-core").PgColumn<{
            name: "auth_tokens_encrypted";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        accountStatus: import("drizzle-orm/pg-core").PgColumn<{
            name: "account_status";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        platformAuthorityLevel: import("drizzle-orm/pg-core").PgColumn<{
            name: "platform_authority_level";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        expertVerificationStatus: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_verification_status";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        accountReputationScore: import("drizzle-orm/pg-core").PgColumn<{
            name: "account_reputation_score";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        totalAuthorityContent: import("drizzle-orm/pg-core").PgColumn<{
            name: "total_authority_content";
            tableName: "geo_platform_accounts";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        averageContentEngagement: import("drizzle-orm/pg-core").PgColumn<{
            name: "average_content_engagement";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        expertRecognitionSignals: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_recognition_signals";
            tableName: "geo_platform_accounts";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        thoughtLeadershipIndicators: import("drizzle-orm/pg-core").PgColumn<{
            name: "thought_leadership_indicators";
            tableName: "geo_platform_accounts";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        platformGeoSettings: import("drizzle-orm/pg-core").PgColumn<{
            name: "platform_geo_settings";
            tableName: "geo_platform_accounts";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        contentAuthorityStrategy: import("drizzle-orm/pg-core").PgColumn<{
            name: "content_authority_strategy";
            tableName: "geo_platform_accounts";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        expertEngagementApproach: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_engagement_approach";
            tableName: "geo_platform_accounts";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        citationOptimizationConfig: import("drizzle-orm/pg-core").PgColumn<{
            name: "citation_optimization_config";
            tableName: "geo_platform_accounts";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        monthlyExpertInquiries: import("drizzle-orm/pg-core").PgColumn<{
            name: "monthly_expert_inquiries";
            tableName: "geo_platform_accounts";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        consultationRequests: import("drizzle-orm/pg-core").PgColumn<{
            name: "consultation_requests";
            tableName: "geo_platform_accounts";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        authorityConversionRate: import("drizzle-orm/pg-core").PgColumn<{
            name: "authority_conversion_rate";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        leadQualityFromAuthority: import("drizzle-orm/pg-core").PgColumn<{
            name: "lead_quality_from_authority";
            tableName: "geo_platform_accounts";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "geo_platform_accounts";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "geo_platform_accounts";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        lastActivity: import("drizzle-orm/pg-core").PgColumn<{
            name: "last_activity";
            tableName: "geo_platform_accounts";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const authorityContentPublications: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "authority_content_publications";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        personaId: import("drizzle-orm/pg-core").PgColumn<{
            name: "persona_id";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        platformAccountId: import("drizzle-orm/pg-core").PgColumn<{
            name: "platform_account_id";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        contentTitle: import("drizzle-orm/pg-core").PgColumn<{
            name: "content_title";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        contentType: import("drizzle-orm/pg-core").PgColumn<{
            name: "content_type";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        contentCategory: import("drizzle-orm/pg-core").PgColumn<{
            name: "content_category";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        contentUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "content_url";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        contentLength: import("drizzle-orm/pg-core").PgColumn<{
            name: "content_length";
            tableName: "authority_content_publications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        authorityScore: import("drizzle-orm/pg-core").PgColumn<{
            name: "authority_score";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        aiCitationPotentialScore: import("drizzle-orm/pg-core").PgColumn<{
            name: "ai_citation_potential_score";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        viewCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "view_count";
            tableName: "authority_content_publications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        engagementCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "engagement_count";
            tableName: "authority_content_publications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        shareCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "share_count";
            tableName: "authority_content_publications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        expertRecognitionSignals: import("drizzle-orm/pg-core").PgColumn<{
            name: "expert_recognition_signals";
            tableName: "authority_content_publications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        consultationInquiriesAttributed: import("drizzle-orm/pg-core").PgColumn<{
            name: "consultation_inquiries_attributed";
            tableName: "authority_content_publications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        leadConversionsAttributed: import("drizzle-orm/pg-core").PgColumn<{
            name: "lead_conversions_attributed";
            tableName: "authority_content_publications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        revenueAttributed: import("drizzle-orm/pg-core").PgColumn<{
            name: "revenue_attributed";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        publicationStatus: import("drizzle-orm/pg-core").PgColumn<{
            name: "publication_status";
            tableName: "authority_content_publications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        publishedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "published_at";
            tableName: "authority_content_publications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "authority_content_publications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "authority_content_publications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const proxyAssignments: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "proxy_assignments";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        personaId: import("drizzle-orm/pg-core").PgColumn<{
            name: "persona_id";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        proxyProvider: import("drizzle-orm/pg-core").PgColumn<{
            name: "proxy_provider";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        proxyType: import("drizzle-orm/pg-core").PgColumn<{
            name: "proxy_type";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        proxyLocation: import("drizzle-orm/pg-core").PgColumn<{
            name: "proxy_location";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        proxyHostEncrypted: import("drizzle-orm/pg-core").PgColumn<{
            name: "proxy_host_encrypted";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        proxyPortEncrypted: import("drizzle-orm/pg-core").PgColumn<{
            name: "proxy_port_encrypted";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        proxyUsernameEncrypted: import("drizzle-orm/pg-core").PgColumn<{
            name: "proxy_username_encrypted";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        proxyPasswordEncrypted: import("drizzle-orm/pg-core").PgColumn<{
            name: "proxy_password_encrypted";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        proxyStatus: import("drizzle-orm/pg-core").PgColumn<{
            name: "proxy_status";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        lastHealthCheck: import("drizzle-orm/pg-core").PgColumn<{
            name: "last_health_check";
            tableName: "proxy_assignments";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        healthCheckStatus: import("drizzle-orm/pg-core").PgColumn<{
            name: "health_check_status";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        connectionSuccessRate: import("drizzle-orm/pg-core").PgColumn<{
            name: "connection_success_rate";
            tableName: "proxy_assignments";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        averageResponseTime: import("drizzle-orm/pg-core").PgColumn<{
            name: "average_response_time";
            tableName: "proxy_assignments";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        assignedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "assigned_at";
            tableName: "proxy_assignments";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "proxy_assignments";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "proxy_assignments";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const expertPersonasNameIdx: import("drizzle-orm/pg-core").IndexBuilder;
export declare const expertPersonasStatusIdx: import("drizzle-orm/pg-core").IndexBuilder;
export declare const expertPersonasAuthorityIdx: import("drizzle-orm/pg-core").IndexBuilder;
export declare const geoPlatformAccountsPersonaIdx: import("drizzle-orm/pg-core").IndexBuilder;
export declare const geoPlatformAccountsPlatformIdx: import("drizzle-orm/pg-core").IndexBuilder;
export declare const contentPublicationsPersonaIdx: import("drizzle-orm/pg-core").IndexBuilder;
export declare const contentPublicationsPlatformIdx: import("drizzle-orm/pg-core").IndexBuilder;
export declare const proxyAssignmentsPersonaIdx: import("drizzle-orm/pg-core").IndexBuilder;
export type AdminUser = typeof adminUsers.$inferSelect;
export type NewAdminUser = typeof adminUsers.$inferInsert;
export type ExpertPersona = typeof expertPersonas.$inferSelect;
export type NewExpertPersona = typeof expertPersonas.$inferInsert;
export type GeoPlatformAccount = typeof geoPlatformAccounts.$inferSelect;
export type NewGeoPlatformAccount = typeof geoPlatformAccounts.$inferInsert;
export type AuthorityContentPublication = typeof authorityContentPublications.$inferSelect;
export type NewAuthorityContentPublication = typeof authorityContentPublications.$inferInsert;
export type ProxyAssignment = typeof proxyAssignments.$inferSelect;
export type NewProxyAssignment = typeof proxyAssignments.$inferInsert;
//# sourceMappingURL=schema.d.ts.map